server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comiteDeAgua
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: example@gmail.com
    password: example
    protocol: smtp
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false # Activa STARTTLS para encriptación TLS, o false para SSL

  main:
    allow-circular-references: true
